version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python manage.py migrate && python manage.py runserver"
    ports:
      - 8000:8000      
    volumes:
      - .:/app 
    depends_on:
      - db    
    env_file:
      - .env
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Buttonup3
      - POSTGRES_DB=devopshire    
volumes:
  postgres_data:

