# Generated by Django 3.2.5 on 2021-08-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerDjango', '0003_alter_sentiment_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
